-- CUSTOMER
INSERT INTO customer ("NAME","SURNAME","EMAIL","PHONE","ADDRESS","WALLET_BALANCE")VALUES('Ali','Private','ali@gmail.com','111111111','İstanbul',151.81);
INSERT INTO customer ("NAME","SURNAME","EMAIL","PHONE","ADDRESS","WALLET_BALANCE")VALUES('Veli','Private','ali@gmail.com','222222222','İstanbul',384.99);
INSERT INTO customer ("NAME","SURNAME","EMAIL","PHONE","ADDRESS","WALLET_BALANCE")VALUES('Emre','Private','emre@gmail.com','333333333','İzmir',10.00);
INSERT INTO customer ("NAME","SURNAME","EMAIL","PHONE","ADDRESS","WALLET_BALANCE")VALUES('Kerem','Private','kerem@gmail.com','345567889','Ankara',76.25);

-- BOOK
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('Tutunamayanlar','Oğuz Atay','724','Türkçe',9789754700114,1984,50.99);
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('Bülbülü Öldürmek','Harper Lee','357','Türkçe',9789755706849,2014,28.33);
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('The Life Before Us','Emile Ajar','192','İngilizce',9780811209618,1986,23.49);
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('Notre Dame''ın Kamburu','Victor Hugo','572','Türkçe',9786053320104,2014,21.99);
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('Karamazov Kardeşler','Fyodor Dostoyevski','1025','Türkçe',9789944880985,2007,29.00);
INSERT INTO book ("TITLE","AUTHOR","NUMBER_OF_PAGES","EDITED_LANGUAGE","ISBN","PUBLISHED_YEAR","PRICE") VALUES ('Semaver','Sait Faik Abasıyanık','138','Türkçe',9786053608851,2013,9.99);


-- STOCK
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (1,3);
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (2,9);
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (3,1);
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (4,1);
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (5,8);
INSERT INTO stock ("BOOK_ID","QUANTITY") VALUES (6,3);